namespace NourishNet.Models.Enums
{
    public enum District
    {
        AMPARA, ANURADHAPURA, BADULAA, BATTICALOA, COLOMBO,
        GALLE, GAMPAHA, HAMBANTHOTA, JAFFNA, KALUTHARA,
        KANDY, KEGALLE, KILINOCHCHI, KURUNEGALA, MANNER,
        MATALE, MATARA, MONARAGALA, MULLAITIVU, NUWARA_ELIYA,
        POLLANNARUWA, PUTTALAM, RATHNAPURA, TRINCOMALEE, VAVUNIYA
    }
}
