export enum Province {
    CENTRAL = 'CENTRAL', 
    EASTERN = 'EASTERN', 
    NORTH_CENTRAL = 'NORTH_CENTRAL',
    NORTHERN = 'NORTHERN', 
    NORTH_WESTERN = 'NORTH_WESTERN', 
    SABARAGAMUWA = 'SABARAGAMUWA',
    SOUTHERN = 'SOUTHERN', 
    UVA = 'UVA', 
    WESTERN = 'WESTERN'
}