pipeline {
    agent any

    environment{
        NETLIFY_SITE_ID = credentials('nourishnet-siteID')
        NETLIFY_AUTH_TOKEN = credentials('netlify-token')
        //me tokens dws 60kin expire wena mokk hari awlk unoth passe kraddi poddk token ek blnna 
    }

    stages {
        stage('Checkout'){
            steps{
                //this is because my repo is not private , if my repo was private i have to provide git crednetials in envrionment section
                git branch : 'master',  url:'https://github.com/indura08/NourishNet-Web-Application.git'
            }
        }

        stage('build frontend') {
            agent {
                docker {
                    image 'node:20-alpine'
                    reuseNode true
                }
            }
            steps {
                dir('frontend/NourishNet'){
                    sh ''' 
                        node --version
                        npm --version 
                        npm ci
                        npx vite build
                    '''
                }
            }
        }

        stage ("deploy"){
            agent {
                docker {
                    image 'node:20-alpine'
                    reuseNode true
                }
            }
            steps{
                sh ''' 
                    npm install netlify-cli
                    node_modules/.bin/netlify --version
                    echo "deploying to prodcution. Site id: $NETLIFY_SITE_ID"
                    node_modules/.bin/netlify status
                    node_modules/.bin/netlify deploy --dir=frontend/NourishNet/dist --prod
                    
                '''
            }

        }
        
    }

    
}
